### ISSUE TITLE
请问安装步骤的替换是什么意思，用哪里的文件去替换呢

### ISSUE THREAD

**Issue by TakayashikiMatsuri** [17TheWord/HarukaBot_Guild_Patch#1]

**Comment by 17TheWord** [comment]
因为比较懒，并没有上传realeases，可以直接下载 [main分支](https://github.com/17TheWord/HarukaBot_Guild_Patch/archive/refs/heads/main.zip) 获取文件  
在 `plugins` 文件内，对照着 **安装** 去替换文件就行了

另外需要注意的是：`频道补丁` `gocq` `nb` 貌似都更新了，我还没来得及更新（测试了下还有些许毛病，就没更新），不过只用 `haruka` 的话够用了

**Comment by TakayashikiMatsuri** [comment]
请问修改的版本要怎么样才可以使用，原版和修改版都折腾了半天还是会报错很多
